### ***Question 1--> Student Performance Analyzer***

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv("/content/StudentMarksDataset.csv")
data

,Std_RollNo,Std_Name,Std_Branch,Std_Course,Std_StudyHours,Std_Marks
0,240415,Tanya Gautam,MC,B.Sc 1st year,6.83,78.50
1,240416,Udit Sagan,MC,B.Sc 1st year,6.56,76.74
2,240417,Kratika Sharma,PM,B.Sc 1st year,NaN,78.68
3,240418,Rakesh Kumar,PM,B.Sc 1st year,5.67,71.82
4,240419,Ritika Katara,PM,B.Sc 1st year,8.67,84.19
...,...,...,...,...,...,...
195,240609,PAYAL,CS,B.Tech 4th year,7.53,81.67
196,240610,SACHIN,CS,B.Tech 4th year,8.56,84.68
197,240611,DOLLY AGRAWAL,ZOOLOGY,B.Tech 4th year,8.94,86.75
198,240612,ROHIT YADAV,ZOOLOGY,B.Tech 4th year,6.60,78.05
199,240613,MAHESH SHARMA,BOTANY,B.Tech 4th year,8.35,83.50

In [ ]:
data["Average"] = data[["Std_StudyHours", "Std_Marks"]].mean(axis=1)
data

,Std_RollNo,Std_Name,Std_Branch,Std_Course,Std_StudyHours,Std_Marks,Average
0,240415,Tanya Gautam,MC,B.Sc 1st year,6.83,78.50,42.665
1,240416,Udit Sagan,MC,B.Sc 1st year,6.56,76.74,41.650
2,240417,Kratika Sharma,PM,B.Sc 1st year,NaN,78.68,78.680
3,240418,Rakesh Kumar,PM,B.Sc 1st year,5.67,71.82,38.745
4,240419,Ritika Katara,PM,B.Sc 1st year,8.67,84.19,46.430
...,...,...,...,...,...,...,...
195,240609,PAYAL,CS,B.Tech 4th year,7.53,81.67,44.600
196,240610,SACHIN,CS,B.Tech 4th year,8.56,84.68,46.620
197,240611,DOLLY AGRAWAL,ZOOLOGY,B.Tech 4th year,8.94,86.75,47.845
198,240612,ROHIT YADAV,ZOOLOGY,B.Tech 4th year,6.60,78.05,42.325
199,240613,MAHESH SHARMA,BOTANY,B.Tech 4th year,8.35,83.50,45.925

In [ ]:
top_10 = data.sort_values(by="Std_Marks", ascending=False).head(10)
top_10

,Std_RollNo,Std_Name,Std_Branch,Std_Course,Std_StudyHours,Std_Marks,Average
182,240596,ANAMIKA,ZOOLOGY,M.Sc 2st Year,8.66,86.99,47.825
197,240611,DOLLY AGRAWAL,ZOOLOGY,B.Tech 4th year,8.94,86.75,47.845
57,240472,Debaditya,BOTANY,M.Sc 1st Year,8.93,86.65,47.790
41,240456,Muskan,CHEMISTRY,B.Sc Honours,8.92,86.41,47.665
149,240563,ROHIT KUMAR PAL,MATHS,B.Sc 2nd Year,8.97,86.12,47.545
138,240553,VAISHNAVI PANDEY,CHEMISTRY,B.Sc 1st year,8.71,85.98,47.345
176,240590,SUPRIYA GUPTA,CS,B.Tech 3rd year,8.93,85.96,47.445
125,240540,ANJALI YADAV,CHEMISTRY,B.Tech 4th year,8.75,85.95,47.350
64,240479,Shubham Mishra,CHEMISTRY,M.Sc 2st Year,8.88,85.78,47.330
55,240470,Govind Kushwah,CS,M.Sc 1st Year,8.69,85.48,47.085

In [ ]:
highest_per_branch = data.groupby('Std_Branch')['Std_Marks'].max().reset_index()
highest_per_branch

        Std_Branch  Std_Marks
0      AGRICULTURE      85.11
1   APPLIED BOTANY      82.27
2               BC      83.88
3           BOTANY      86.65
4               BZ      83.33
5        CHEMISTRY      86.41
6               CS      85.96
7            MATHS      86.12
8               MC      80.81
9          PHYSICS      84.24
10              PM      84.19
11              ZC      85.46
12         ZOOLOGY      86.99

In [ ]:
def assign_grade(marks):
    if marks >= 85:
        return 'A'
    elif marks >= 75:
        return 'B'
    elif marks >= 65:
        return 'C'
    elif marks >= 50:
        return 'D'
    else:
        return 'F'
data['Grade'] = data['Std_Marks'].apply(assign_grade)
data

,Std_RollNo,Std_Name,Std_Branch,Std_Course,Std_StudyHours,Std_Marks,Average,Grade
0,240415,Tanya Gautam,MC,B.Sc 1st year,6.83,78.50,42.665,B
1,240416,Udit Sagan,MC,B.Sc 1st year,6.56,76.74,41.650,B
2,240417,Kratika Sharma,PM,B.Sc 1st year,NaN,78.68,78.680,B
3,240418,Rakesh Kumar,PM,B.Sc 1st year,5.67,71.82,38.745,C
4,240419,Ritika Katara,PM,B.Sc 1st year,8.67,84.19,46.430,B
...,...,...,...,...,...,...,...,...
195,240609,PAYAL,CS,B.Tech 4th year,7.53,81.67,44.600,B
196,240610,SACHIN,CS,B.Tech 4th year,8.56,84.68,46.620,B
197,240611,DOLLY AGRAWAL,ZOOLOGY,B.Tech 4th year,8.94,86.75,47.845,A
198,240612,ROHIT YADAV,ZOOLOGY,B.Tech 4th year,6.60,78.05,42.325,B
199,240613,MAHESH SHARMA,BOTANY,B.Tech 4th year,8.35,83.50,45.925,B

In [ ]:
data.describe()

          Std_RollNo  Std_StudyHours  Std_Marks     Average
count     200.000000      195.000000  200.00000  200.000000
mean   240514.200000        6.995949   77.93375   43.338175
std        57.515215        1.253060    4.92570    6.197393
min    240415.000000        5.010000   68.57000   36.885000
25%    240464.750000        5.775000   73.38500   39.600000
50%    240514.500000        7.120000   77.71000   42.552500
75%    240563.250000        8.085000   82.32000   45.462500
max    240613.000000        8.990000   86.99000   78.680000

### ***Question 2***

In [ ]:
import pandas as pd
data = pd.read_csv("/content/archive (3).zip")
data

    age  experience  income
0    50           5   45118
1    36           9   41691
2    29           3   35994
3    42           5   41614
4    40          12   51474
5    44          14   57092
6    32           1   31661
7    32           9   42378
8    45          11   50099
9    57           1   35800
10   45           9   49959
11   24          13   48575
12   43           3   37504
13   23          13   47998
14   45          14   53954
15   51          14   56945
16   59           7   51047
17   23          13   44204
18   42           6   41331
19   54          11   55691
20   33           8   41673
21   43          13   50970
22   46           7   46356
23   48           4   42981
24   49          12   52390
25   37           1   33440
26   36          14   49828
27   24           4   30702
28   58           7   49393
29   28           9   39770
30   42           8   46088
31   30          11   42706
32   39          11   50334
33   25          11   46977
34   46          12   50284
35   35           8   40363
36   30          12   46790
37   47          14   52663
38   23          12   47016
39   41           0   33491
40   49           8   45457
41   28           6   36078
42   29           8   40942
43   56           7   48936
44   35           0   28559
45   38          11   50179
46   57           7   46322
47   25           7   38314
48   23          14   48057
49   27          10   46015

In [ ]:
dept_avg = data.groupby("experience")["income"].mean()
dept_avgdept_avg = data.groupby("experience")["income"].mean()
dept_avg

experience
0     31025.000000
1     33633.666667
3     36749.000000
4     36841.500000
5     43366.000000
6     38704.500000
7     46728.000000
8     42904.600000
9     43449.500000
10    46015.000000
11    49331.000000
12    49590.800000
13    47936.750000
14    53089.833333
Name: income, dtype: float64

In [ ]:
highest_paid = data.loc[data['income'].idxmax()]
highest_paid

age              44
experience       14
income        57092
Name: 5, dtype: int64

In [ ]:
lowest_paid = data.loc[data['income'].idxmin()]
lowest_paid

age              35
experience        0
income        28559
Name: 44, dtype: int64

In [ ]:
print("=== INCOME BY EXPERIENCE===")
for k, v in data.groupby(pd.cut(data['experience'], bins=[-1, 3, 7, 11, 15]), observed=False)['income'].mean().items():
    print(f"{str(k):<18} | {'█' * int(v/2000)} ${v:,.0f}")
print("\n=== INCOME BY AGE GROUP ===")
for k, v in data.groupby(pd.cut(data['age'], bins=[20, 30, 40, 50, 60]), observed=False)['income'].mean().items():
    print(f"{str(k):<18} | {'█' * int(v/2000)} ${v:,.0f}")

=== INCOME BY EXPERIENCE===
(-1, 3]            | ████████████████ $33,778
(3, 7]             | █████████████████████ $43,183
(7, 11]            | ██████████████████████ $45,645
(11, 15]           | █████████████████████████ $50,549

=== INCOME BY AGE GROUP ===
(20, 30]           | █████████████████████ $42,676
(30, 40]           | ████████████████████ $41,962
(40, 50]           | ███████████████████████ $46,903
(50, 60]           | ████████████████████████ $49,162

In [ ]:
data.describe()

             age  experience        income
count  50.000000   50.000000     50.000000
mean   38.860000    8.580000  44864.060000
std    10.719066    4.116121   6916.729587
min    23.000000    0.000000  28559.000000
25%    29.250000    6.250000  41039.250000
50%    39.500000    9.000000  46205.000000
75%    46.000000   12.000000  50064.000000
max    59.000000   14.000000  57092.000000

### ***Some Important Series Methods:***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
subs = pd.read_csv('/content/subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [ ]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [ ]:
import sys
sys.getsizeof(vk)

3472

In [ ]:
sys.getsizeof(vk.astype('int16'))

2182

In [ ]:
vk[vk['runs'].between(51,99)].size

43

In [ ]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [ ]:
temp.drop_duplicates(keep='last')

1    1
3    2
5    3
7    4
dtype: int64

In [ ]:
temp.duplicated().sum()

np.int64(4)

In [ ]:
vk.duplicated().sum()

np.int64(137)

In [ ]:
movies.drop_duplicates()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Sssshhh...                            Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                Tanuja
Right Here Right Now (film)                      Ankit
Talaash: The Hunt Begins...              Rakhee Gulzar
The Pink Mirror                        Edwin Fernandes

[566 rows x 1 columns]

In [ ]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

0     1.0
1     2.0
2     3.0
3     NaN
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [ ]:
temp.size

10

In [ ]:
temp.count()

np.int64(7)

In [ ]:
temp.isnull().sum()

np.int64(3)

In [ ]:
temp.dropna()

0     1.0
1     2.0
2     3.0
4     5.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [ ]:
temp.fillna(temp.mean())

0     1.0
1     2.0
2     3.0
3     5.0
4     5.0
5     6.0
6     5.0
7     8.0
8     5.0
9    10.0
dtype: float64

In [ ]:
vk[vk['runs'].isin([49,99])]

          runs
match_no
82          99
86          49

In [ ]:
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [ ]:
movies['lead'].str.split().str[0].str.upper()

movie
Uri: The Surgical Strike                  VICKY
Battalion 609                             VICKY
The Accidental Prime Minister (film)     ANUPAM
Why Cheat India                          EMRAAN
Evening Shadows                            MONA
                                         ...
Hum Tumhare Hain Sanam                     SHAH
Aankhen (2002 film)                     AMITABH
Saathiya (film)                           VIVEK
Company (film)                             AJAY
Awara Paagal Deewana                     AKSHAY
Name: lead, Length: 1500, dtype: object

In [ ]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
mean_value = subs['Subscribers gained'].mean()
subs['Day_Quality'] = subs['Subscribers gained'].apply(lambda x: 'good day' if x > mean_value else 'bad day')
subs

     Subscribers gained Day_Quality
0                    48     bad day
1                    57     bad day
2                    40     bad day
3                    43     bad day
4                    44     bad day
..                  ...         ...
360                 231    good day
361                 226    good day
362                 155    good day
363                 144    good day
364                 172    good day

[365 rows x 2 columns]

In [ ]:
subs.mean(numeric_only=True)

Subscribers gained    135.643836
dtype: float64

In [ ]:
new = vk.head()

In [ ]:
new = vk.head().copy()
new

          runs
match_no
1            1
2           23
3           13
4           12
5            1